from __future__ import annotations

from typing import Protocol

from src.runtime.specs import ProbeResult, ProbeSpec, RosbagSpec, RuntimeHandle, ServiceSpec


class RuntimeBackend(Protocol):
    @property
    def name(self) -> str: ...

    def start_service(self, spec: ServiceSpec) -> RuntimeHandle: ...

    def start_rosbag(self, spec: RosbagSpec) -> RuntimeHandle: ...

    def run_probe(self, spec: ProbeSpec) -> ProbeResult: ...

    def wait(self, handle: RuntimeHandle, *, timeout_sec: float | None = None) -> int: ...

    def stop(self, handle: RuntimeHandle, *, timeout_sec: float = 5.0) -> None: ...

    def logs(self, handle: RuntimeHandle | str, *, tail: int = 400) -> str: ...
